import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const INSTALL = path.resolve(__dirname, "..", "scripts", "install.sh");

describe("curl installer", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-install-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execFileSync("bash", [INSTALL], {
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
      stdio: "pipe",
    }).toString();

  it("archives a historical workflow and creates the canonical workflow", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );

    const output = run();
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(canonical).toContain("Generated by robin-review");
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");
    expect(
      fs.existsSync(
        path.join(dir, ".github", "robin-workflow-archive", "code-review.yml.disabled"),
      ),
    ).toBe(true);
  });

  it("is idempotent after migration", () => {
    run({ ROBIN_REF: "v1" });

    const output = run();
    const canonical = fs.readFileSync(
      path.join(dir, ".github", "workflows", "robin.yml"),
      "utf8",
    );

    expect(output).toContain("is already current");
    expect(canonical).toContain("review.yml@v1");
  });
});
