import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const INSTALL = path.resolve(__dirname, "..", "scripts", "install.sh");

describe("curl installer", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-install-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execFileSync("bash", [INSTALL], {
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
      stdio: "pipe",
    }).toString();

  it("archives a historical workflow and creates the canonical workflow", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );

    const output = run();
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(canonical).toContain("Generated by robin-review");
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");
    expect(
      fs.existsSync(
        path.join(dir, ".github", "robin-workflow-archive", "code-review.yml.disabled"),
      ),
    ).toBe(true);

    fs.copyFileSync(
      path.join(dir, ".github", "robin-workflow-archive", "code-review.yml.disabled"),
      path.join(workflows, "code-review.yml"),
    );
    const duplicateOutput = run();
    expect(duplicateOutput).toContain(
      "Removed .github/workflows/code-review.yml (identical copy already at .github/robin-workflow-archive/code-review.yml.disabled)",
    );
  });

  it("is idempotent after migration", () => {
    run({ ROBIN_REF: "v1" });

    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const lfWorkflow = fs.readFileSync(workflowPath, "utf8");
    fs.writeFileSync(workflowPath, lfWorkflow.replace(/\n/g, "\r\n"));

    const output = run();
    const canonical = fs.readFileSync(workflowPath, "utf8");

    expect(output).toContain("is already current");
    expect(canonical).toContain("review.yml@v1");
    expect(canonical).toContain("\r\n");
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("uses a numbered archive when the first destination has different content", () => {
    const workflows = path.join(dir, ".github", "workflows");
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    fs.mkdirSync(workflows, { recursive: true });
    fs.mkdirSync(archive, { recursive: true });
    const legacy =
      "name: Universal\r Code Reviewer\r\njobs:\r\n  review:\r\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\r\n";
    fs.writeFileSync(path.join(workflows, "code-review.yml"), legacy);
    fs.writeFileSync(
      path.join(archive, "code-review.yml.disabled"),
      legacy.replace("Universal\r Code", "Universal Code"),
    );

    run();

    expect(fs.readFileSync(path.join(archive, "code-review.yml.1.disabled"), "utf8")).toBe(
      legacy,
    );
  });
});
