import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const BIN = path.resolve(__dirname, "..", "bin", "robin-review.js");

describe("robin-review CLI", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-bin-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execSync(`node "${BIN}"`, {
      stdio: "pipe",
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
    }).toString();

  it("creates the canonical workflow with the given ref", () => {
    run({ ROBIN_REF: "v2" });

    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const workflow = fs.readFileSync(workflowPath, "utf8");
    expect(workflow).toContain("Generated by robin-review");
    expect(workflow).toContain("uses: antongulin/robin/.github/workflows/review.yml@v2");
    expect(workflow).toContain("LLM_API_KEY: ${{ secrets.LLM_API_KEY }}");
  });

  it("is idempotent and keeps an existing modern ref", () => {
    run({ ROBIN_REF: "v1" });
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const before = fs.readFileSync(workflowPath, "utf8");

    const output = run();

    expect(output).toContain("is already current");
    expect(fs.readFileSync(workflowPath, "utf8")).toBe(before);
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("archives historical workflow names and variants before creating the canonical file", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );
    fs.writeFileSync(
      path.join(workflows, "ai-review.yaml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: antongulin/robin@main\n",
    );
    fs.writeFileSync(
      path.join(workflows, "legacy-action.yml"),
      "name: Code Review\njobs:\n  review:\n    steps:\n      - uses: antongulin/universal-code-reviewer@main\n",
    );

    const output = run();
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(output).toContain("Multiple Robin workflows found; using default ref (main)");
    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(output).toContain("Archived .github/workflows/ai-review.yaml");
    expect(output).toContain("Archived .github/workflows/legacy-action.yml");
    expect(fs.existsSync(path.join(workflows, "code-review.yml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "ai-review.yaml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "legacy-action.yml"))).toBe(false);
    expect(fs.existsSync(path.join(archive, "code-review.yml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "ai-review.yaml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "legacy-action.yml.disabled"))).toBe(true);
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");

    fs.copyFileSync(
      path.join(archive, "code-review.yml.disabled"),
      path.join(workflows, "code-review.yml"),
    );
    const duplicateOutput = run();
    expect(duplicateOutput).toContain(
      "Removed .github/workflows/code-review.yml (identical copy already at .github/robin-workflow-archive/code-review.yml.disabled)",
    );
  });

  it("archives an older canonical workflow while preserving its modern ref", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(
      workflowPath,
      "name: Robin\njobs:\n  review:\n    uses: antongulin/robin/.github/workflows/review.yml@v1\n",
    );

    run();

    expect(fs.readFileSync(workflowPath, "utf8")).toContain("review.yml@v1");
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "robin.yml.disabled")),
    ).toBe(true);
  });

  it("uses a numbered archive when the first destination has different content", () => {
    const workflows = path.join(dir, ".github", "workflows");
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    fs.mkdirSync(workflows, { recursive: true });
    fs.mkdirSync(archive, { recursive: true });
    const legacy =
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n";
    fs.writeFileSync(path.join(workflows, "code-review.yml"), legacy);
    fs.writeFileSync(path.join(archive, "code-review.yml.disabled"), "different archive\n");

    run();

    expect(fs.readFileSync(path.join(archive, "code-review.yml.1.disabled"), "utf8")).toBe(
      legacy,
    );
  });

  it("refuses to overwrite an unrelated canonical workflow", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(workflowPath, "name: Unrelated automation\n");

    expect(() => run()).toThrow();
    expect(fs.readFileSync(workflowPath, "utf8")).toBe("name: Unrelated automation\n");
  });

  it("does not add a consumer workflow to Robin's source repository", () => {
    fs.writeFileSync(path.join(dir, "package.json"), '{"name":"robin-review"}\n');
    fs.writeFileSync(path.join(dir, "action.yml"), "name: Robin\n");
    fs.mkdirSync(path.join(dir, "skills", "robin"), { recursive: true });
    fs.writeFileSync(path.join(dir, "skills", "robin", "SKILL.md"), "# Robin\n");
    fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
    fs.writeFileSync(path.join(dir, ".github", "workflows", "self-test.yml"), "name: Self-Test\n");

    const output = run();

    expect(output).toContain("Robin source repository detected");
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("rejects a ROBIN_REF with YAML metacharacters", () => {
    expect(() => run({ ROBIN_REF: "main\njobs: {}" })).toThrow();
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("fails outside a git repository", () => {
    const bare = fs.mkdtempSync(path.join(os.tmpdir(), "robin-nogit-"));
    try {
      expect(() =>
        cp.execSync(`node "${BIN}"`, {
          cwd: bare,
          env: { ...process.env, ROBIN_SKILL: "0" },
          stdio: "pipe",
        })
      ).toThrow();
    } finally {
      fs.rmSync(bare, { recursive: true, force: true });
    }
  });

  it("is tracked as an executable npm binary", () => {
    expect(fs.statSync(BIN).mode & 0o111).not.toBe(0);
  });
});
